### ISSUE TITLE
宿舍晚上断电断网吗？

### ISSUE THREAD

**Issue by gylidian** [needhourger/nuist_README#7]
夏季(大概从5月底开始) 不断电
冬季 **23:30**(工作日) **23:50**(周末) 左右开始断电 (除了空调插座)

ipv4网 晚上 **23:50** 左右开始中断
ipv6网 不断的 (但据说现在晚上也开始断了 _还没考证_)

以上中断 均在 次日 **7点** 恢复

**Comment by gylidian** [comment]
**温馨提示**：
尽量少熬夜，等你工作了有的是时间熬夜（想不熬都不行）
如果要熬夜的话，请确保你开热点消耗的流量在套餐范围内（足够的流量）

**Comment by needhourger** [comment]
@gylidian  已经更新关于断电断网的贴士
